### ISSUE TITLE
Need larger IPA diacritics 

### ISSUE THREAD

**Issue by sharoncorrell** [silnrsi/font-charis#10]
We are using Charis for ScriptSource, and running into a problem in the phoneme/grapheme system. Some of the IPA diacritics are so small that they are really hard to read. It's an obstacle specifically to one of our teams who would like to use the RTR feature for some of their data, but the "right tack below" is almost indistinguishable from similar symbols.

Would there  be any way for some of the diacritics to enlarged? Or could somebody build me a one-off font just for ScriptSource with the modifications? (I'd be willing to do the changes, but the build process is beyond me. Or is there a way to make changes somehow without having to rebuild?)

Specifically:
0318 - left tack below
0319 - right tack below
0320 - under-bar
031F - plus sign below
0329 - vertical bar below

Also:
0325 - ring
030A - ring
0303 - tilde
0330 - tilde below

OR - does anybody know of a font with bigger diacritics?

**Comment by jvgaultney** [comment]
Be sure you're using the latest version of Charis, as the hinting is improved and small shapes will likely be clearer. Those diacritics (except ring) are proportionally larger in Gentium - again use the latest version.

Making a special version of Charis for ScriptSource is possible but it locks us into a cycle of producing a unique version every time we update the fonts. It would be better to add a larger diacritics feature for these (and maybe other diacs) although that would take a while to design and produce (due to many other issues in the queue).

Ping me when you get in the office and we can chat about the options.
